# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/36-cloud-base"
  config.vm.hostname = "nomad-dev"

  config.vm.network "forwarded_port", guest: 4646, host: 4646 # The Nomad UI/CLI port
  config.vm.network "forwarded_port", guest: 8000, host: 8000 # Open port for example apps, etc.

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yaml"
  end
end
