# A playbook for installing and configuring Nomad

- name: Nomad
  hosts: all
  become: true
  tasks:
    - name: Install Nomad and Docker
      include_tasks: "../common/nomad.yaml"

    - name: Configure Nomad
      blockinfile:
        path: /etc/nomad.d/nomad.hcl
        block: |
          plugin "docker" {
            config {
              allow_privileged = true
              volumes {
                enabled = true
              }
            }
          }

    - name: Restart Nomad
      systemd:
        name: nomad
        state: restarted
